### ISSUE TITLE
Need @Transactional annotation when you test your code with Stream API in Java

### ISSUE THREAD

**Issue by thelovemsg** [thelovemsg/chatting_app#7]
## Result
> Need @Transactional annotation when you test your code with Stream API in Java
## detailed situation
- I've treid to test my code in jUnit5 and i'm fetching data with Stream API. 
- Error occured when i tried it. I asked chatGPT to help us to know why this happens.

just read it!

_The @Transactional annotation is needed because the streaming query method you're using requires an open database connection to consume the returned Stream. When using streaming queries, it is essential to keep the connection open so that the underlying JDBC ResultSet can read the data incrementaThe @Transactional annotation is needed because the streaming query method you're using requires an open database connection to consume the returned Stream. When using streaming queries, it is essential to keep the connection open so that the underlying JDBC ResultSet can read the data incrementally as the Stream is being consumed.

When you call this method without an active transaction, 
the connection is closed before you can consume the returned Stream, and this is why you get the InvalidDataAccessApiUsageException.

By adding the @Transactional annotation to the test method, you're telling the Spring framework to start a transaction before the method is executed and commit or rollback the transaction after the method has finished execution. This ensures that the database connection stays open while you're consuming the Stream, thus avoiding the exception.

It is important to note that if you were using a non-streaming query (e.g., returning a List instead of a Stream), you wouldn't necessarily need the @Transactional annotation, because the connection would only need to be open while the query is executed and the data is fetched. The connection can be safely closed after the data is fetched, and this is typically managed automatically by the Spring framework.

me : why Stream must be consumes?

chatGPT : A Stream in Java represents a sequence of elements that can be processed in parallel or sequentially. The main purpose of using a Stream is to perform operations on the elements without actually storing them in memory. This can be particularly useful when dealing with large datasets, as it allows you to process data on-the-fly without loading the entire dataset into memory.

When you use a Stream, the data is not processed or fetched until you explicitly consume it. Consuming a Stream means performing a terminal operation on it, such as collect(), forEach(), toArray(), or reduce(). These terminal operations trigger the processing of the data in the Stream and return a result or a side-effect based on the intermediate operations (like filter(), map(), etc.) applied to the Stream.

In the context of your JPA query, using a Stream allows you to process the query results as they are fetched from the database, rather than loading all the results into memory at once. This can help you avoid out-of-memory errors and improve performance when working with large result sets.

However, the Stream must be consumed to actually fetch and process the data. If you don't consume the Stream, the query results are never fetched or processed, which essentially defeats the purpose of using a Stream in the first place. Additionally, not consuming the Stream may lead to resource leaks, as the underlying database connection and other associated resources may not be closed or released properly. This is why it is important to always consume a Stream and ensure that any resources tied to it are properly managed.lly as the Stream is being consumed.

**Comment by KrGil** [comment]
그래서 이해했나요?

**Comment by thelovemsg** [comment]
> 그래서 이해했나요?
Yes, babe
